- hosts: all
  tasks:
    - name: download coredns
      get_url:
        url: https://github.com/coredns/coredns/releases/download/v1.11.1/coredns_1.11.1_linux_amd64.tgz
        dest: /root/
    - name: mkdir
      file:
        path: /root/coredns
        state: directory
    - name: unarchive
      unarchive:
        src: /root/coredns_1.11.1_linux_amd64.tgz
        remote_src: yes
        dest: /root/coredns
    - name: copy config
      copy:
        src: ./coredns_config
        dest: /root/coredns/
    - name: systemd-resolve disable
      systemd:
        name: systemd-resolved
        state: stopped
        enabled: false
    - name: setting crontab
      cron:
        name: "job for coredns"
        special_time: reboot
        job: /root/coredns/coredns -conf /root/coredns/coredns_config/config
